<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class RegisterType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', TextType::Class, array(
            'label' => 'Nombre'
        ))
            ->add('email', TextType::Class, array(
                'label' => 'Email'
            ))
            -> add('passw',TextType::Class, array(
                'label' => 'Nombre'
            ))
            -> add('name',TextType::Class, array(
                'label' => 'Nombre'
            ))

        ;
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
}